/**
 * Bundles the starter project into the editor, art included, so the first thing
 * a new user sees is a game they can play rather than an empty screen.
 *
 * It is the same starter `pinforge new` copies, with its assets inlined as data
 * URIs exactly as the exporter does.
 */
import { readFileSync, writeFileSync } from 'node:fs';
import { dirname, extname, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

const here = dirname(fileURLToPath(import.meta.url));
const template = resolve(here, '../../cli/templates/starter');
const output = resolve(here, '../src/starter.generated.ts');

const TYPES = {
  '.png': 'image/png',
  '.jpg': 'image/jpeg',
  '.jpeg': 'image/jpeg',
  '.gif': 'image/gif',
  '.webp': 'image/webp',
  '.wav': 'audio/wav',
  '.mp3': 'audio/mpeg',
  '.ogg': 'audio/ogg',
};

const project = JSON.parse(readFileSync(`${template}/game.pinforge.json`, 'utf8'));
project.assets = project.assets.map((asset) => {
  const type = TYPES[extname(asset.source).toLowerCase()];
  if (!type) throw new Error(`The starter uses ${asset.source}, which cannot be inlined.`);
  const bytes = readFileSync(resolve(template, asset.source));
  return { ...asset, source: `data:${type};base64,${bytes.toString('base64')}` };
});

writeFileSync(
  output,
  `// Generated by scripts/build-starter.mjs. Do not edit.\n` +
    `import type { ProjectInput } from '@pinforge/schema';\n\n` +
    `export const STARTER: ProjectInput = ${JSON.stringify(project, null, 2)} as ProjectInput;\n`,
);
process.stdout.write(`starter bundled: ${(JSON.stringify(project).length / 1024).toFixed(0)} kB\n`);
